### ISSUE TITLE
Newly created indexes

### ISSUE THREAD

**Issue by DigitalMaxim** [MITRECND/snugglefish#7]
Hello,
Should I change name for newly created indexes before replacing them to the directory specified in CRITs? I see that a new index has exactly the same name as previous old index - CW.index00000000. If I move new index (all three files) to the directory with an old index it will replace it. Is it OK?
Thanks

**Comment by wxsBSD** [comment]
No, you don't want to change the name. When adding new files to an existing index you need to have the old index around so that snugglefish can recognize that and append to the existing index.
